# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('identificacion', models.IntegerField(unique=True)),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('localizacion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anio_fabricacion', models.PositiveIntegerField()),
                ('tranmision', models.CharField(choices=[('MA', 'Manual'), ('AU', 'Automática')], max_length=30)),
                ('tipo_vehiculo', models.CharField(choices=[('4WD', '4x4'), ('2WD', '4x2')], max_length=3)),
                ('pais_ensamblaje', models.CharField(choices=[('BRA', 'Brasil'), ('ARG', 'Argentina'), ('JAP', 'Japón'), ('GBN', 'Inglaterra')], max_length=11)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Vitrina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('numero_vendedores', models.IntegerField()),
                ('localizacion', models.CharField(max_length=30)),
                ('concesionario_perteneciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experimento_1.Concesionario')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vitrina_muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experimento_1.Vitrina'),
        ),
    ]
