# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experimento_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1111111)]),
        ),
        migrations.AlterField(
            model_name='concesionario',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
