# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experimento_1', '0002_auto_20170929_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesionario',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vitrina',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
