# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experimento_1', '0003_auto_20170929_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1111111)]),
        ),
    ]
