# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experimento_1', '0004_auto_20170930_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='pais_ensamblaje',
            field=models.CharField(choices=[('Brasil', 'Brasil'), ('Argentina', 'Argentina'), ('Japón', 'Japón'), ('Inglaterra', 'Inglaterra')], max_length=11),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('4x4', '4x4'), ('4x2', '4x2')], max_length=3),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tranmision',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automática', 'Automática')], max_length=30),
        ),
    ]
