# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Experimento_1', '0005_auto_20171001_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)], verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ocupacion',
            field=models.CharField(max_length=50, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1111111)], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='concesionario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='concesionario',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='concesionario',
            name='localizacion',
            field=models.CharField(max_length=50, verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio_fabricacion',
            field=models.PositiveIntegerField(verbose_name='Año fabricación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='pais_ensamblaje',
            field=models.CharField(choices=[('Brasil', 'Brasil'), ('Argentina', 'Argentina'), ('Japón', 'Japón'), ('Inglaterra', 'Inglaterra')], max_length=11, verbose_name='País ensamblaje'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('4x4', '4x4'), ('4x2', '4x2')], max_length=3, verbose_name='Tipo Vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tranmision',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automática', 'Automática')], max_length=30, verbose_name='Transmisión'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vitrina_muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experimento_1.Vitrina', verbose_name='Vitrina muestra'),
        ),
        migrations.AlterField(
            model_name='vitrina',
            name='concesionario_perteneciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experimento_1.Concesionario', verbose_name='Concesionario'),
        ),
        migrations.AlterField(
            model_name='vitrina',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='vitrina',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='vitrina',
            name='localizacion',
            field=models.CharField(max_length=30, verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='vitrina',
            name='numero_vendedores',
            field=models.IntegerField(verbose_name='Número de Vendedores'),
        ),
    ]
