# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Experimento_1', '0006_auto_20171002_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='vitrina_muestra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Experimento_1.Vitrina', verbose_name='Vitrina muestra'),
        ),
        migrations.AlterField(
            model_name='vitrina',
            name='concesionario_perteneciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Experimento_1.Concesionario', verbose_name='Concesionario'),
        ),
    ]
